### ISSUE TITLE
was ist hywin

### ISSUE THREAD

**Issue by lretq** [mlgdabest509/HywinWpf#1]
sheeeeeeeeeeesh

**Comment by mlgdabest509** [comment]
Chat app für C# mit Ende zu Ende Verschlüsselung, Github ist für Auto
Updates

Cook1e ***@***.***> schrieb am Mo., 6. Sept. 2021, 19:40:

**Comment by mlgdabest509** [comment]
Bitte aber noch nicht installieren, war nur ein Test Commit um Autoupdate zu testen.
